19 CI conda support (#30)
* CI: feat: conda build

* fix: requirements_frozen.txt got new name

* CI: fix: CondaValueError: prefix already exists: /usr/share/miniconda/envs/selectzyme

* CI: fix: GitHub Actions does not allow modifying GITHUB_ENV with a direct conda activate command. Instead, you should use the correct syntax provided by setup-miniconda, which automatically activates the environment if you specify activate-environment

* CI: finally test the loading from cache, miniconda setup is 4m 37s and cache writing is 3m 44s
totalling < 10min

* fix: docker: port forwarding

* fix: docker: eda: raise TypeCheckError(f"did not match any element in the union:\n{formatted_errors}")
typeguard.TypeCheckError: argument "config_file" (None) did not match any element in the union:
  pathlib.Path: is not an instance of pathlib.Path
  str: is not an instance of str

* fix: when 1st click is on tree no list but dict is used
AttributeError: 'dict' object has no attribute 'append'

* CI: revert: perf: use mamba: Did not find Mambaforge-Linux-x86_64.sh latest in cache

* CI: reading cache was only 1m faster and other errors occured. last try: delete cache, use mamba and run 2 times. else revert and dont create cache

* CI: revert all caching. Didnt speed up much anyways

* CI: fix: ENOENT: no such file or directory, open '/home/runner/work/ec/ec/environment.yml'