Qdrant database usage (docker) (#27)
* feat: access qdrant from docker container

* fix: deprecated collection.vectors_count
can be collection.points_count but is also not needed i guess
!is needed, else only 10 points are loaded and cause collection to be deleted

* CI: tests: wontfix
Client.__init__() got an unexpected keyword argument 'location'
urllib3.exceptions.LocationParseError: Failed to parse: :memory: